[build]
  publish = "."
  command = ""

[functions]
  directory = "serverless/netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/studio.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: https:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; upgrade-insecure-requests;"

